# Generated by Django 3.0.3 on 2020-02-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        ('eat', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='eat_log',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eat.Log'),
        ),
        migrations.AddField(
            model_name='users',
            name='gym_log',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='gym.Log'),
        ),
    ]
