# Generated by Django 3.0.3 on 2020-02-10 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eat', '0001_initial'),
        ('gym', '0001_initial'),
        ('login', '0002_auto_20200210_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='eat_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat.Log'),
        ),
        migrations.AlterField(
            model_name='users',
            name='gym_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.Log'),
        ),
    ]
