# Generated by Django 3.0.3 on 2020-02-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200211_0808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='eat_log',
        ),
        migrations.RemoveField(
            model_name='users',
            name='gym_log',
        ),
    ]
