# Generated by Django 3.0.3 on 2020-02-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Exercise Date')),
                ('sets', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('exercise_id', models.IntegerField()),
            ],
        ),
    ]
